# Site settings
lang: en
name: Marc
title: Marc — Theoretical Physics & Systems Biology
email: marc@example.edu
description: >-
Professor of Theoretical Physics and Systems Biology. Research on stochastic processes, multi-scale modeling, and complex biological networks.

# If this is your personal site repo (yourusername.github.io):
url: https://milenaw.github.io/milenaweiershausen.github.io/
baseurl: "" # leave blank for personal-site repo; for a project site use: /repo-name

# Theme and build
plugins:
- jekyll-scholar
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap

# Navigation (matches Home, Research, Talks & Lectures, Contact)
navbar:
entries:
- title: Home
url: /
- title: Research
url: /research/
- title: Talks & Lectures
url: /talks/
- title: Contact
url: /contact/

# Social links (edit as needed)
social:
email: marc@example.edu
google_scholar: https://scholar.google.com/citations?user=XXXX
orcid: https://orcid.org/0000-0000-0000-0000
github: https://github.com/yourusername
twitter: https://twitter.com/yourhandle
linkedin: https://www.linkedin.com/in/yourprofile/

# SEO
timezone: Europe/Berlin
permalink: /:categories/:title/

# Collections / defaults (optional minimal)
collections:
pages:
output: true

# jekyll-scholar (for publications)
scholar:
style: apa
source: _bibliography
bibliography: papers.bib
bibliography_template: bibliography
sort_by: year
order: descending

# Theme options (al-folio-compatible keys)
layouts_home:
title: "Marc"
subtitle: "Professor, TU Somewhere"
image: /assets/img/headshot.jpg
